sections:
  - title: ละครไทย (ออนแอร์)
    subtitle: Thai Dramas
  - title: ข่าว
    subtitle: News
  - title: ทอล์กโชว์
    subtitle: Talk Shows
  - title: ซีรี่ย์เกาหลี (เสียงไทย)
    subtitle: Korean Series
  - title: วาไรตี้โชว์
    subtitle: Variety Shows
  - title: ภาพยนตร์ฝรั่งใหม่
    subtitle: Hollywood Movies
  - title: หนังไทยใหม่ & โชวหม่
    subtitle: Thai Movies
  - title: ซิทคอม
    subtitle: Sitcom
  - title: เกมส์โชว์
    subtitle: Game Shows
  - title: ซีรี่ย์ฝรั่ง
    subtitle: US Series
